
// This file has been generated by the GUI designer. Do not modify.
namespace chipConf
{
	public partial class LogWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button buttonClear;

		private global::Gtk.Entry entryCommand;

		private global::Gtk.Button button1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget chipConf.LogWindow
			this.Name = "chipConf.LogWindow";
			this.Title = "LogWindow";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(3));
			this.AllowShrink = true;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Container child chipConf.LogWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView();
			this.textview3.CanFocus = true;
			this.textview3.Events = ((global::Gdk.EventMask)(2097152));
			this.textview3.Name = "textview3";
			this.textview3.Editable = false;
			this.textview3.CursorVisible = false;
			this.textview3.AcceptsTab = false;
			this.textview3.WrapMode = ((global::Gtk.WrapMode)(1));
			this.GtkScrolledWindow.Add(this.textview3);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonClear = new global::Gtk.Button();
			this.buttonClear.CanFocus = true;
			this.buttonClear.Name = "buttonClear";
			this.buttonClear.UseUnderline = true;
			this.buttonClear.Label = "Очистить лог";
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-delete", global::Gtk.IconSize.Button);
			this.buttonClear.Image = w3;
			this.hbox2.Add(this.buttonClear);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonClear]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryCommand = new global::Gtk.Entry();
			this.entryCommand.CanFocus = true;
			this.entryCommand.Name = "entryCommand";
			this.entryCommand.IsEditable = true;
			this.entryCommand.ActivatesDefault = true;
			this.entryCommand.InvisibleChar = '•';
			this.hbox2.Add(this.entryCommand);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entryCommand]));
			w5.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = "Отправить";
			global::Gtk.Image w6 = new global::Gtk.Image();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-ok", global::Gtk.IconSize.Button);
			this.button1.Image = w6;
			this.hbox2.Add(this.button1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button1]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 628;
			this.DefaultHeight = 300;
			this.Show();
			this.DestroyEvent += new global::Gtk.DestroyEventHandler(this.EventOnDestroy);
			this.buttonClear.Clicked += new global::System.EventHandler(this.EventClearLog);
			this.button1.Clicked += new global::System.EventHandler(this.EventSendCommand);
		}
	}
}
