
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action Action;

	private global::Gtk.Action ActionReadSpecsList;

	private global::Gtk.Action ActionResetSpecs;

	private global::Gtk.Action ActionWriteSpecs;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox headLine;

	private global::Gtk.Button buttonReadSpecs;

	private global::Gtk.Button buttonWriteSpecs;

	private global::Gtk.Button buttonReset;

	private global::Gtk.Button buttonToggleLog;

	private global::Gtk.Button buttonRestartDevice;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.Table table4;

	private global::Gtk.Statusbar statusbar1;

	private global::Gtk.Label labelStatus;

	private global::Gtk.Label labelHost;

	private global::Gtk.Entry entryHost;

	private global::Gtk.Label labelPort;

	private global::Gtk.SpinButton portSelector;

	private global::Gtk.Button buttonConnect;

	private global::Gtk.Button buttonDisconnect;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.Action = new global::Gtk.Action("Action", "Управление настройками", null, null);
		this.Action.ShortLabel = "Управление настройками";
		w1.Add(this.Action, null);
		this.ActionReadSpecsList = new global::Gtk.Action("ActionReadSpecsList", "Считать перечень настроек", null, null);
		this.ActionReadSpecsList.ShortLabel = "Считать перечень настроек";
		w1.Add(this.ActionReadSpecsList, "<Mod2>r");
		this.ActionResetSpecs = new global::Gtk.Action("ActionResetSpecs", "Сбросить настройки до базовых", null, null);
		this.ActionResetSpecs.ShortLabel = "Сбросить настройки до базовых";
		w1.Add(this.ActionResetSpecs, "<Primary><Mod2>d");
		this.ActionWriteSpecs = new global::Gtk.Action("ActionWriteSpecs", "Записать изменения", null, null);
		this.ActionWriteSpecs.ShortLabel = "Записать изменения";
		w1.Add(this.ActionWriteSpecs, "<Primary><Mod2>s");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = "ChipLANProg";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.headLine = new global::Gtk.HBox();
		this.headLine.Name = "headLine";
		this.headLine.Spacing = 6;
		// Container child headLine.Gtk.Box+BoxChild
		this.buttonReadSpecs = new global::Gtk.Button();
		this.buttonReadSpecs.Sensitive = false;
		this.buttonReadSpecs.CanFocus = true;
		this.buttonReadSpecs.Name = "buttonReadSpecs";
		this.buttonReadSpecs.UseUnderline = true;
		this.buttonReadSpecs.Label = "Считать настройки";
		global::Gtk.Image w2 = new global::Gtk.Image();
		w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.Button);
		this.buttonReadSpecs.Image = w2;
		this.headLine.Add(this.buttonReadSpecs);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.headLine[this.buttonReadSpecs]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child headLine.Gtk.Box+BoxChild
		this.buttonWriteSpecs = new global::Gtk.Button();
		this.buttonWriteSpecs.Sensitive = false;
		this.buttonWriteSpecs.CanFocus = true;
		this.buttonWriteSpecs.Name = "buttonWriteSpecs";
		this.buttonWriteSpecs.UseUnderline = true;
		this.buttonWriteSpecs.Label = "Записать";
		global::Gtk.Image w4 = new global::Gtk.Image();
		w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
		this.buttonWriteSpecs.Image = w4;
		this.headLine.Add(this.buttonWriteSpecs);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.headLine[this.buttonWriteSpecs]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child headLine.Gtk.Box+BoxChild
		this.buttonReset = new global::Gtk.Button();
		this.buttonReset.Sensitive = false;
		this.buttonReset.CanFocus = true;
		this.buttonReset.Name = "buttonReset";
		this.buttonReset.UseUnderline = true;
		this.buttonReset.Label = "Сбросить до заводских";
		this.headLine.Add(this.buttonReset);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.headLine[this.buttonReset]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child headLine.Gtk.Box+BoxChild
		this.buttonToggleLog = new global::Gtk.Button();
		this.buttonToggleLog.CanFocus = true;
		this.buttonToggleLog.Name = "buttonToggleLog";
		this.buttonToggleLog.UseUnderline = true;
		this.buttonToggleLog.Label = "Лог";
		global::Gtk.Image w7 = new global::Gtk.Image();
		w7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-file", global::Gtk.IconSize.Button);
		this.buttonToggleLog.Image = w7;
		this.headLine.Add(this.buttonToggleLog);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.headLine[this.buttonToggleLog]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		// Container child headLine.Gtk.Box+BoxChild
		this.buttonRestartDevice = new global::Gtk.Button();
		this.buttonRestartDevice.Sensitive = false;
		this.buttonRestartDevice.CanFocus = true;
		this.buttonRestartDevice.Name = "buttonRestartDevice";
		this.buttonRestartDevice.UseUnderline = true;
		this.buttonRestartDevice.Label = "Перезагрузить устройство";
		this.headLine.Add(this.buttonRestartDevice);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.headLine[this.buttonRestartDevice]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add(this.headLine);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.headLine]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w11 = new global::Gtk.Viewport();
		w11.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.table4 = new global::Gtk.Table(((uint)(1)), ((uint)(3)), true);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		w11.Add(this.table4);
		this.GtkScrolledWindow.Add(w11);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w14.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.labelStatus = new global::Gtk.Label();
		this.labelStatus.Name = "labelStatus";
		this.labelStatus.LabelProp = "Disconnected";
		this.statusbar1.Add(this.labelStatus);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.labelStatus]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.labelHost = new global::Gtk.Label();
		this.labelHost.Name = "labelHost";
		this.labelHost.LabelProp = "Host/IP:";
		this.statusbar1.Add(this.labelHost);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.labelHost]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.entryHost = new global::Gtk.Entry();
		this.entryHost.CanFocus = true;
		this.entryHost.Name = "entryHost";
		this.entryHost.Text = "127.0.0.1";
		this.entryHost.IsEditable = true;
		this.entryHost.WidthChars = 8;
		this.entryHost.InvisibleChar = '•';
		this.statusbar1.Add(this.entryHost);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.entryHost]));
		w17.Position = 3;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.labelPort = new global::Gtk.Label();
		this.labelPort.Name = "labelPort";
		this.labelPort.LabelProp = "Port:";
		this.statusbar1.Add(this.labelPort);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.labelPort]));
		w18.Position = 4;
		w18.Expand = false;
		w18.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.portSelector = new global::Gtk.SpinButton(1D, 65535D, 1D);
		this.portSelector.CanFocus = true;
		this.portSelector.Name = "portSelector";
		this.portSelector.Adjustment.PageIncrement = 10D;
		this.portSelector.ClimbRate = 1D;
		this.portSelector.Numeric = true;
		this.portSelector.Value = 8080D;
		this.statusbar1.Add(this.portSelector);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.portSelector]));
		w19.Position = 5;
		w19.Expand = false;
		w19.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.buttonConnect = new global::Gtk.Button();
		this.buttonConnect.CanFocus = true;
		this.buttonConnect.Name = "buttonConnect";
		this.buttonConnect.UseUnderline = true;
		this.buttonConnect.Label = "Подключиться";
		global::Gtk.Image w20 = new global::Gtk.Image();
		w20.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-connect", global::Gtk.IconSize.Menu);
		this.buttonConnect.Image = w20;
		this.statusbar1.Add(this.buttonConnect);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.buttonConnect]));
		w21.Position = 6;
		w21.Expand = false;
		w21.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.buttonDisconnect = new global::Gtk.Button();
		this.buttonDisconnect.Sensitive = false;
		this.buttonDisconnect.CanFocus = true;
		this.buttonDisconnect.Name = "buttonDisconnect";
		this.buttonDisconnect.UseUnderline = true;
		this.buttonDisconnect.Label = "Отключиться";
		global::Gtk.Image w22 = new global::Gtk.Image();
		w22.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-disconnect", global::Gtk.IconSize.Menu);
		this.buttonDisconnect.Image = w22;
		this.statusbar1.Add(this.buttonDisconnect);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.buttonDisconnect]));
		w23.Position = 7;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox1.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 776;
		this.DefaultHeight = 372;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.buttonReadSpecs.Clicked += new global::System.EventHandler(this.EventReadSpecsClicked);
		this.buttonWriteSpecs.Clicked += new global::System.EventHandler(this.EventWriteSpecsClicked);
		this.buttonReset.Clicked += new global::System.EventHandler(this.EventResetDeviceClicked);
		this.buttonToggleLog.Clicked += new global::System.EventHandler(this.eventLogDisplayingToggle);
		this.buttonRestartDevice.Clicked += new global::System.EventHandler(this.EventRebootDeviceClicked);
		this.buttonConnect.Clicked += new global::System.EventHandler(this.EventButtonConnectClicked);
		this.buttonDisconnect.Clicked += new global::System.EventHandler(this.OnButtonDisconnectClicked);
	}
}
